student:main.o header.o stud_add.o print.o rev_print.o stud_del.o stud_del_all.o stud_mode.o save.o stud_sort.o
	cc main.c header.c stud_add.c print.c rev_print.c stud_del.c stud_del_all.c stud_mode.c save.c stud_sort.c -o student
main.o:main.c
	cc -c main.c
header.o:header.c
	cc -c header.c
stud_add.o:stud_add.c
	cc -c stud_add.c
print.o:print.c
	cc -c print.c
rev_print.o:rev_print.c
	cc -c rev_print.c
stud_del.o:stud_del.c
	cc -c stud_del.c
stud_del_all.o:stud_del_all.c
	cc -c stud_del_all.c
stud_mod.o:stud_mode.c
	cc -c stud_mode.c
save.o:save.c
	cc -c save.c
stud_sort.o:stud_sort.c
	cc -c stud_sort.c
